# Generated by Django 3.0.5 on 2020-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('year', models.IntegerField(max_length=4)),
                ('period', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
